name = "piccini-brasil-2030"
compatibility_date = "2026-08-05"
main = "./worker.js"
workers_dev = true

[[routes]]
pattern = "brasil-2030.piccini.app"
custom_domain = true

[assets]
directory = "./dist"
binding = "ASSETS"
html_handling = "none"
not_found_handling = "404-page"
run_worker_first = true

[[d1_databases]]
binding = "DB"
database_name = "brasil-2030-supporters"
database_id = "1c7425d7-306d-40ea-804e-3b7dd94a7bdc"
